apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcc-registry
  labels:
    app: vcc-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcc-registry
  template:
    metadata:
      labels:
        app: vcc-registry
    spec:
      containers:
      - name: vcc-registry
        image: nttb/vcc-registry:v1
        ports:
        - containerPort: 8080