apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vcc-registry
  name: vcc-registry
  selfLink: /api/v1/namespaces/default/services/vcc-registry
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30783
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vcc-registry
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
