{
 "title": "VCC - ShowCase",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pools",
    "label": "Deployed VCC Pools",
    "query": "label_values(kube_deployment_labels{deployment=~\"vcc-service-[\\\\d]*\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Common Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    },
    {
     "title": "System Pods",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(kube_pod_info{namespace=~\".*system\"}))"
      }
     ]
    },
    {
     "title": "Deployd datapools",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_deployment_labels{label_app=~\"vcc-service-[\\\\d]*\"})"
      }
     ]
    },
    {
     "title": "Pods per Node",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sort_desc(sum(kube_pod_info{node!=\"\"}) by(node))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "HTTP Requests per Pool",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(rate(http_server_requests_seconds_count [5m])) by(app))",
       "legendFormat": "{{app}}"
      },
      {
       "expr": "round(sum(rate(http_server_requests_seconds_count [5m])) by())",
       "legendFormat": "{{system}}"
      }
     ]
    }
   ]
  },
  { "title": "$pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "pools" },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_app=\"$pools\"})"
    }
   ]
  },
  {
   "title": "Running Since",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 2 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()- kube_deployment_created{deployment=~\"$pools\"}"
    }
   ]
  },
  {
   "title": "CPU and Memory consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"$pools\"}[1h]))by(container_name)",
     "legendFormat": "rate_container_cpu_usage_seconds_total_1h"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$pools\"})/1000000",
     "legendFormat": "jvm_memory_used_bytes"
    }
   ]
  }
 ]
}