apiVersion: v1
kind: Service
metadata:
  name: vcc-status-repository
  labels:
    app: vcc-status-repository
spec:
  selector:
    app: vcc-status-repository
  ports:
  - protocol: TCP
    port: 30268
    targetPort: 8080
