apiVersion: v1
kind: Pod
metadata:
  name: vcc-pool
  labels:
    app: vcc-pool
spec:
  containers:
  - name: vcc-pool
    image: mysql:5.6
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: admin123
    - name: MYSQL_USER
      value: "admin"
    - name: MYSQL_PASSWORD
      value: "admin123"
    - name: MYSQL_DATABASE
      value: vcc_pool

