apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vcc-pool
  name: vcc-pool-external
  selfLink: /api/v1/namespaces/default/services/vcc-pool-external
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30267
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: vcc-pool
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
