apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vcc-service-1
  name: vcc-service-1-external
  selfLink: /api/v1/namespaces/default/services/vcc-service-1-external
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31610
    port: 3309
    protocol: TCP
    targetPort: 9010
  selector:
    app: vcc-service-1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
