apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: vcc-service-1
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vcc-service-1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: http_requests_seconds_rate
      targetAverageValue: 20
